sudo: false
language: go
env:
- GO111MODULE=on
go:
- 1.11.x
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
git:
  depth: 1
install: true
notifications:
  email: false
before_install:
# https://docs.travis-ci.com/user/encrypting-files/
- openssl aes-256-cbc -K $encrypted_cdc6351ed5c5_key -iv $encrypted_cdc6351ed5c5_iv
  -in mailman-summarizer-7cd37e4f2137.json.enc -out mailman-summarizer-7cd37e4f2137.json
  -d
- gcloud version
- gcloud auth activate-service-account --key-file=mailman-summarizer-7cd37e4f2137.json
install:
- gcloud config set project mailman-summarizer
script:
- go build
deploy:
- gsutil stat gs://ceph-rgw-users/LICENSE
